export interface StateData {
  abbreviation: string;
  name: string;
  cities: string[];
}

export const US_STATES: StateData[] = [
  { abbreviation: 'AL', name: 'Alabama', cities: ['Birmingham', 'Huntsville', 'Mobile', 'Montgomery', 'Tuscaloosa'] },
  { abbreviation: 'AK', name: 'Alaska', cities: ['Anchorage', 'Fairbanks', 'Juneau'] },
  { abbreviation: 'AZ', name: 'Arizona', cities: ['Phoenix', 'Tucson', 'Mesa', 'Scottsdale', 'Chandler', 'Tempe'] },
  { abbreviation: 'AR', name: 'Arkansas', cities: ['Little Rock', 'Fayetteville', 'Fort Smith', 'Bentonville'] },
  { abbreviation: 'CA', name: 'California', cities: ['Los Angeles', 'San Francisco', 'San Diego', 'San Jose', 'Sacramento', 'Oakland', 'Irvine', 'Fresno', 'Long Beach', 'Anaheim'] },
  { abbreviation: 'CO', name: 'Colorado', cities: ['Denver', 'Colorado Springs', 'Aurora', 'Fort Collins', 'Boulder'] },
  { abbreviation: 'CT', name: 'Connecticut', cities: ['Hartford', 'New Haven', 'Stamford', 'Bridgeport', 'Waterbury'] },
  { abbreviation: 'DE', name: 'Delaware', cities: ['Wilmington', 'Dover', 'Newark'] },
  { abbreviation: 'FL', name: 'Florida', cities: ['Miami', 'Orlando', 'Tampa', 'Jacksonville', 'Fort Lauderdale', 'St. Petersburg', 'Naples', 'Sarasota'] },
  { abbreviation: 'GA', name: 'Georgia', cities: ['Atlanta', 'Savannah', 'Augusta', 'Columbus', 'Athens'] },
  { abbreviation: 'HI', name: 'Hawaii', cities: ['Honolulu', 'Hilo', 'Kailua'] },
  { abbreviation: 'ID', name: 'Idaho', cities: ['Boise', 'Meridian', 'Nampa', 'Idaho Falls'] },
  { abbreviation: 'IL', name: 'Illinois', cities: ['Chicago', 'Springfield', 'Naperville', 'Rockford', 'Peoria'] },
  { abbreviation: 'IN', name: 'Indiana', cities: ['Indianapolis', 'Fort Wayne', 'Evansville', 'South Bend', 'Carmel'] },
  { abbreviation: 'IA', name: 'Iowa', cities: ['Des Moines', 'Cedar Rapids', 'Davenport', 'Iowa City'] },
  { abbreviation: 'KS', name: 'Kansas', cities: ['Wichita', 'Overland Park', 'Kansas City', 'Topeka', 'Olathe'] },
  { abbreviation: 'KY', name: 'Kentucky', cities: ['Louisville', 'Lexington', 'Bowling Green', 'Frankfort'] },
  { abbreviation: 'LA', name: 'Louisiana', cities: ['New Orleans', 'Baton Rouge', 'Shreveport', 'Lafayette'] },
  { abbreviation: 'ME', name: 'Maine', cities: ['Portland', 'Bangor', 'Augusta'] },
  { abbreviation: 'MD', name: 'Maryland', cities: ['Baltimore', 'Bethesda', 'Rockville', 'Annapolis', 'Frederick'] },
  { abbreviation: 'MA', name: 'Massachusetts', cities: ['Boston', 'Cambridge', 'Worcester', 'Springfield', 'Lowell'] },
  { abbreviation: 'MI', name: 'Michigan', cities: ['Detroit', 'Grand Rapids', 'Ann Arbor', 'Lansing', 'Kalamazoo'] },
  { abbreviation: 'MN', name: 'Minnesota', cities: ['Minneapolis', 'St. Paul', 'Rochester', 'Duluth', 'Bloomington'] },
  { abbreviation: 'MS', name: 'Mississippi', cities: ['Jackson', 'Gulfport', 'Biloxi', 'Hattiesburg'] },
  { abbreviation: 'MO', name: 'Missouri', cities: ['Kansas City', 'St. Louis', 'Springfield', 'Columbia', 'Jefferson City'] },
  { abbreviation: 'MT', name: 'Montana', cities: ['Billings', 'Missoula', 'Great Falls', 'Helena', 'Bozeman'] },
  { abbreviation: 'NE', name: 'Nebraska', cities: ['Omaha', 'Lincoln', 'Bellevue'] },
  { abbreviation: 'NV', name: 'Nevada', cities: ['Las Vegas', 'Reno', 'Henderson', 'North Las Vegas'] },
  { abbreviation: 'NH', name: 'New Hampshire', cities: ['Manchester', 'Nashua', 'Concord'] },
  { abbreviation: 'NJ', name: 'New Jersey', cities: ['Newark', 'Jersey City', 'Trenton', 'Princeton', 'Atlantic City'] },
  { abbreviation: 'NM', name: 'New Mexico', cities: ['Albuquerque', 'Santa Fe', 'Las Cruces', 'Rio Rancho'] },
  { abbreviation: 'NY', name: 'New York', cities: ['New York', 'Brooklyn', 'New York City', 'Buffalo', 'Rochester', 'Albany', 'Syracuse'] },
  { abbreviation: 'NC', name: 'North Carolina', cities: ['Charlotte', 'Raleigh', 'Durham', 'Greensboro', 'Wilmington', 'Asheville'] },
  { abbreviation: 'ND', name: 'North Dakota', cities: ['Fargo', 'Bismarck', 'Grand Forks', 'Minot'] },
  { abbreviation: 'OH', name: 'Ohio', cities: ['Columbus', 'Cleveland', 'Cincinnati', 'Toledo', 'Akron', 'Dayton'] },
  { abbreviation: 'OK', name: 'Oklahoma', cities: ['Oklahoma City', 'Tulsa', 'Norman', 'Broken Arrow'] },
  { abbreviation: 'OR', name: 'Oregon', cities: ['Portland', 'Salem', 'Eugene', 'Bend', 'Medford'] },
  { abbreviation: 'PA', name: 'Pennsylvania', cities: ['Philadelphia', 'Pittsburgh', 'Harrisburg', 'Allentown', 'Erie'] },
  { abbreviation: 'RI', name: 'Rhode Island', cities: ['Providence', 'Warwick', 'Cranston', 'Newport'] },
  { abbreviation: 'SC', name: 'South Carolina', cities: ['Charleston', 'Columbia', 'Greenville', 'Myrtle Beach'] },
  { abbreviation: 'SD', name: 'South Dakota', cities: ['Sioux Falls', 'Rapid City', 'Aberdeen'] },
  { abbreviation: 'TN', name: 'Tennessee', cities: ['Nashville', 'Memphis', 'Knoxville', 'Chattanooga', 'Clarksville'] },
  { abbreviation: 'TX', name: 'Texas', cities: ['Houston', 'Dallas', 'Austin', 'San Antonio', 'Fort Worth', 'El Paso', 'Plano', 'Frisco'] },
  { abbreviation: 'UT', name: 'Utah', cities: ['Salt Lake City', 'Provo', 'Ogden', 'St. George', 'Park City'] },
  { abbreviation: 'VT', name: 'Vermont', cities: ['Burlington', 'Montpelier', 'Rutland'] },
  { abbreviation: 'VA', name: 'Virginia', cities: ['Virginia Beach', 'Richmond', 'Arlington', 'Norfolk', 'Alexandria', 'Roanoke'] },
  { abbreviation: 'WA', name: 'Washington', cities: ['Seattle', 'Spokane', 'Tacoma', 'Bellevue', 'Olympia'] },
  { abbreviation: 'WV', name: 'West Virginia', cities: ['Charleston', 'Huntington', 'Morgantown'] },
  { abbreviation: 'WI', name: 'Wisconsin', cities: ['Milwaukee', 'Madison', 'Green Bay', 'Kenosha'] },
  { abbreviation: 'WY', name: 'Wyoming', cities: ['Cheyenne', 'Casper', 'Laramie', 'Jackson'] },
  { abbreviation: 'DC', name: 'Washington D.C.', cities: ['Washington D.C.'] },
];
